/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ia.Ui;

import java.util.ArrayList;
import java.util.Date;

import com.ia.data.Docente;
import java.text.ParseException;
import java.time.LocalTime;

import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author fuent
 */
public class ingresoDocente extends javax.swing.JFrame {

    /**
     * Creates new form ingresoCursoo
     */
    ArrayList<Docente> docentes;
    Main main;
    public ingresoDocente(ArrayList<Docente> docentes,Main main) {
        initComponents();
        this.docentes = docentes;
        this.main = main;
        configurarCampoHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        registroPersonal = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        horaSalida = new javax.swing.JFormattedTextField();
        horaEntrada = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("NUEVO DOCENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, 126, -1));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 64, -1));

        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("Ingrese el nombre del curso");
        nombre.setBorder(null);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 10));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        jLabel3.setText("HORA ENTRADA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 10));

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        jLabel4.setText("REGISTRO PERSONAL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 76, 150, 20));

        registroPersonal.setForeground(new java.awt.Color(204, 204, 204));
        registroPersonal.setText("Ingrese el nombre del curso");
        registroPersonal.setBorder(null);
        registroPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(registroPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 190, 10));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 13)); // NOI18N
        jLabel5.setText("HORA SALIDA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 190, 10));

        jPanel5.setBackground(new java.awt.Color(58, 92, 209));

        jLabel8.setBackground(new java.awt.Color(58, 92, 209));
        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INGRESAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, 40));

        horaSalida.setBorder(null);
        horaSalida.setText("hora salida");
        horaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(horaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, -1));

        horaEntrada.setBorder(null);
        horaEntrada.setText("hora entrada");
        horaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(horaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void registroPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroPersonalActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Docente tmp = new Docente(nombre.getText(), Long.parseLong(registroPersonal.getText()),LocalTime.parse(horaEntrada.getText()),LocalTime.parse(horaSalida.getText()));
        docentes.add(tmp);
        main.llenarTablaDocente(docentes);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void horaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaSalidaActionPerformed

    private void horaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaEntradaActionPerformed

    private void configurarCampoHora() {
        try {
            MaskFormatter mascara = new MaskFormatter("##:##");
            mascara.setPlaceholderCharacter('_');
            mascara.setValidCharacters("0123456789");
            horaSalida.setFormatterFactory(new DefaultFormatterFactory(mascara)); // Aplica la máscara
            horaSalida.setToolTipText("Ingresa la hora en formato HH:mm (ej: 18:00)");
            horaEntrada.setFormatterFactory(new DefaultFormatterFactory(mascara)); // Aplica la máscara
            horaEntrada.setToolTipText("Ingresa la hora en formato HH:mm (ej: 18:00)");
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField horaEntrada;
    private javax.swing.JFormattedTextField horaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField registroPersonal;
    // End of variables declaration//GEN-END:variables
}
